### PR TITLE
Offer more guidance on how to write good "Short Summary" for issues

### PR DESCRIPTION
**Pull request by Chekote**

### CODE REVIEW

**Comment by Chekote** [comment]
I invited all the Sr lead, along with Lorenzo Gabriel, to make sure everyone is onboard with this change.

**Review by lorenzodalaqua — APPROVED** [review]
I like the final draft with the bullet points even better 👏 

(Some of the typos were bugging me for a long time, happy to see them fixed 🎉)

**Review by smijo149 — APPROVED** [review]
Looks Good!

**Review by rashidsaf — APPROVED** [review]
LGTM

**Review by fortoulrodolfo — APPROVED** [review]
👍

**Review by rleandro83 — APPROVED** [review]
👍

**Review by GLobatoR — APPROVED** [review]
I like the three-level separation between the big-picture and the specific tasks to give context and purpose.

**Pull request merged**
